#!/bin/bash
rm -R ./public
mkdir ./public
cp -R ./assets ./public/assets
# cd ./decks

for i in *.mdx; do
    [ -f "$i" ] || break
    name=${i%.*}
    echo "Processing $i"
    mkdir ./public/$name
    npx mdx-deck build --no-html $i -d ./public/$name
done

# cd ..

# x0 build ./notes/lecture1-notes.mdx -d ./public
